---
abstract: 'Useful testing subclass for Selenium WebDriver!'
author:
  - 'Luke Closs <cpan@5thplane.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-WebDriver
no_index:
  directory:
    - t
    - inc
requires:
  IO::Socket: 0
  Selenium::Remote::Driver: 0
  Test::Builder: 0
  Test::More: 0
version: 0.01
